export const PYTHON_LEVELS = [
  {
    "id": "python_01",
    "language": "python",
    "stage": 1,
    "difficulty": "easy",
    "title": "print พื้นฐาน",
    "description": "ด่าน Python 1: print พื้นฐาน",
    "usage": "แสดงข้อความ Hello Python",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "print(\"Hello Python\")",
    "outputExplain": "แสดงข้อความ Hello Python",
    "output": "แสดงข้อความ Hello Python",
    "basePoints": 112,
    "rewardPoints": 12,
    "timeLimit": 45
  },
  {
    "id": "python_02",
    "language": "python",
    "stage": 2,
    "difficulty": "easy",
    "title": "ตัวแปรข้อความ",
    "description": "ด่าน Python 2: ตัวแปรข้อความ",
    "usage": "เก็บข้อความในตัวแปรแล้วแสดงผล",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "name = \"Pisit\"\nprint(name)",
    "outputExplain": "เก็บข้อความในตัวแปรแล้วแสดงผล",
    "output": "เก็บข้อความในตัวแปรแล้วแสดงผล",
    "basePoints": 124,
    "rewardPoints": 13,
    "timeLimit": 49
  },
  {
    "id": "python_03",
    "language": "python",
    "stage": 3,
    "difficulty": "easy",
    "title": "ตัวแปรตัวเลข",
    "description": "ด่าน Python 3: ตัวแปรตัวเลข",
    "usage": "เก็บจำนวนเต็มและแสดงผล",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "score = 95\nprint(score)",
    "outputExplain": "เก็บจำนวนเต็มและแสดงผล",
    "output": "เก็บจำนวนเต็มและแสดงผล",
    "basePoints": 136,
    "rewardPoints": 15,
    "timeLimit": 47
  },
  {
    "id": "python_04",
    "language": "python",
    "stage": 4,
    "difficulty": "easy",
    "title": "บวกเลข",
    "description": "ด่าน Python 4: บวกเลข",
    "usage": "คำนวณผลบวก",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "a = 12\nb = 8\nprint(a + b)",
    "outputExplain": "คำนวณผลบวก",
    "output": "คำนวณผลบวก",
    "basePoints": 148,
    "rewardPoints": 16,
    "timeLimit": 48
  },
  {
    "id": "python_05",
    "language": "python",
    "stage": 5,
    "difficulty": "easy",
    "title": "คำนวณหลายตัวดำเนินการ",
    "description": "ด่าน Python 5: คำนวณหลายตัวดำเนินการ",
    "usage": "คำนวณราคารวม",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "price = 120\nqty = 3\ntotal = price * qty\nprint(total)",
    "outputExplain": "คำนวณราคารวม",
    "output": "คำนวณราคารวม",
    "basePoints": 160,
    "rewardPoints": 17,
    "timeLimit": 69
  },
  {
    "id": "python_06",
    "language": "python",
    "stage": 6,
    "difficulty": "easy",
    "title": "รับข้อความแนวคิด",
    "description": "ด่าน Python 6: รับข้อความแนวคิด",
    "usage": "แสดงหลายค่าในบรรทัดเดียว",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "student = \"Somchai\"\nlevel = \"ปวช.1\"\nprint(student, level)",
    "outputExplain": "แสดงหลายค่าในบรรทัดเดียว",
    "output": "แสดงหลายค่าในบรรทัดเดียว",
    "basePoints": 172,
    "rewardPoints": 18,
    "timeLimit": 72
  },
  {
    "id": "python_07",
    "language": "python",
    "stage": 7,
    "difficulty": "easy",
    "title": "f-string",
    "description": "ด่าน Python 7: f-string",
    "usage": "แทรกตัวแปรในข้อความด้วย f-string",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "name = \"Ann\"\nscore = 88\nprint(f\"{name}: {score}\")",
    "outputExplain": "แทรกตัวแปรในข้อความด้วย f-string",
    "output": "แทรกตัวแปรในข้อความด้วย f-string",
    "basePoints": 184,
    "rewardPoints": 20,
    "timeLimit": 66
  },
  {
    "id": "python_08",
    "language": "python",
    "stage": 8,
    "difficulty": "easy",
    "title": "boolean",
    "description": "ด่าน Python 8: boolean",
    "usage": "เก็บค่า True/False",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "is_ready = True\nprint(is_ready)",
    "outputExplain": "เก็บค่า True/False",
    "output": "เก็บค่า True/False",
    "basePoints": 196,
    "rewardPoints": 21,
    "timeLimit": 53
  },
  {
    "id": "python_09",
    "language": "python",
    "stage": 9,
    "difficulty": "easy",
    "title": "if พื้นฐาน",
    "description": "ด่าน Python 9: if พื้นฐาน",
    "usage": "ตรวจเงื่อนไข",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "score = 70\nif score >= 50:\n    print(\"Pass\")",
    "outputExplain": "ตรวจเงื่อนไข",
    "output": "ตรวจเงื่อนไข",
    "basePoints": 208,
    "rewardPoints": 22,
    "timeLimit": 63
  },
  {
    "id": "python_10",
    "language": "python",
    "stage": 10,
    "difficulty": "easy",
    "title": "if else",
    "description": "ด่าน Python 10: if else",
    "usage": "เลือกผลลัพธ์สองทาง",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "score = 45\nif score >= 50:\n    print(\"Pass\")\nelse:\n    print(\"Try again\")",
    "outputExplain": "เลือกผลลัพธ์สองทาง",
    "output": "เลือกผลลัพธ์สองทาง",
    "basePoints": 220,
    "rewardPoints": 24,
    "timeLimit": 84
  },
  {
    "id": "python_11",
    "language": "python",
    "stage": 11,
    "difficulty": "easy",
    "title": "if elif else",
    "description": "ด่าน Python 11: if elif else",
    "usage": "ตรวจหลายช่วงคะแนน",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "score = 82\nif score >= 80:\n    print(\"A\")\nelif score >= 70:\n    print(\"B\")\nelse:\n    print(\"C\")",
    "outputExplain": "ตรวจหลายช่วงคะแนน",
    "output": "ตรวจหลายช่วงคะแนน",
    "basePoints": 232,
    "rewardPoints": 25,
    "timeLimit": 101
  },
  {
    "id": "python_12",
    "language": "python",
    "stage": 12,
    "difficulty": "easy",
    "title": "and operator",
    "description": "ด่าน Python 12: and operator",
    "usage": "รวมสองเงื่อนไขด้วย and",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "age = 18\nhas_card = True\nif age >= 18 and has_card:\n    print(\"Allowed\")",
    "outputExplain": "รวมสองเงื่อนไขด้วย and",
    "output": "รวมสองเงื่อนไขด้วย and",
    "basePoints": 244,
    "rewardPoints": 26,
    "timeLimit": 84
  },
  {
    "id": "python_13",
    "language": "python",
    "stage": 13,
    "difficulty": "easy",
    "title": "or operator",
    "description": "ด่าน Python 13: or operator",
    "usage": "ใช้ or เมื่อผ่านได้อย่างใดอย่างหนึ่ง",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "role = \"teacher\"\nif role == \"admin\" or role == \"teacher\":\n    print(\"Access\")",
    "outputExplain": "ใช้ or เมื่อผ่านได้อย่างใดอย่างหนึ่ง",
    "output": "ใช้ or เมื่อผ่านได้อย่างใดอย่างหนึ่ง",
    "basePoints": 256,
    "rewardPoints": 27,
    "timeLimit": 87
  },
  {
    "id": "python_14",
    "language": "python",
    "stage": 14,
    "difficulty": "easy",
    "title": "list",
    "description": "ด่าน Python 14: list",
    "usage": "สร้าง list",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "languages = [\"HTML\", \"CSS\", \"Python\"]\nprint(languages)",
    "outputExplain": "สร้าง list",
    "output": "สร้าง list",
    "basePoints": 268,
    "rewardPoints": 29,
    "timeLimit": 70
  },
  {
    "id": "python_15",
    "language": "python",
    "stage": 15,
    "difficulty": "easy",
    "title": "index list",
    "description": "ด่าน Python 15: index list",
    "usage": "เข้าถึงสมาชิกด้วย index",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "languages = [\"HTML\", \"CSS\", \"Python\"]\nprint(languages[0])",
    "outputExplain": "เข้าถึงสมาชิกด้วย index",
    "output": "เข้าถึงสมาชิกด้วย index",
    "basePoints": 280,
    "rewardPoints": 30,
    "timeLimit": 72
  },
  {
    "id": "python_16",
    "language": "python",
    "stage": 16,
    "difficulty": "medium",
    "title": "append list",
    "description": "ด่าน Python 16: append list",
    "usage": "เพิ่มสมาชิก list",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "scores = [70, 80]\nscores.append(90)\nprint(scores)",
    "outputExplain": "เพิ่มสมาชิก list",
    "output": "เพิ่มสมาชิก list",
    "basePoints": 292,
    "rewardPoints": 30,
    "timeLimit": 66
  },
  {
    "id": "python_17",
    "language": "python",
    "stage": 17,
    "difficulty": "medium",
    "title": "for loop",
    "description": "ด่าน Python 17: for loop",
    "usage": "วนซ้ำสมาชิก",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "for number in [1, 2, 3]:\n    print(number)",
    "outputExplain": "วนซ้ำสมาชิก",
    "output": "วนซ้ำสมาชิก",
    "basePoints": 304,
    "rewardPoints": 31,
    "timeLimit": 61
  },
  {
    "id": "python_18",
    "language": "python",
    "stage": 18,
    "difficulty": "medium",
    "title": "range",
    "description": "ด่าน Python 18: range",
    "usage": "วนซ้ำช่วงตัวเลข",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "for i in range(5):\n    print(i)",
    "outputExplain": "วนซ้ำช่วงตัวเลข",
    "output": "วนซ้ำช่วงตัวเลข",
    "basePoints": 316,
    "rewardPoints": 32,
    "timeLimit": 53
  },
  {
    "id": "python_19",
    "language": "python",
    "stage": 19,
    "difficulty": "medium",
    "title": "while loop",
    "description": "ด่าน Python 19: while loop",
    "usage": "วนซ้ำด้วย while",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "count = 1\nwhile count <= 3:\n    print(count)\n    count += 1",
    "outputExplain": "วนซ้ำด้วย while",
    "output": "วนซ้ำด้วย while",
    "basePoints": 328,
    "rewardPoints": 33,
    "timeLimit": 74
  },
  {
    "id": "python_20",
    "language": "python",
    "stage": 20,
    "difficulty": "medium",
    "title": "break",
    "description": "ด่าน Python 20: break",
    "usage": "หยุด loop ด้วย break",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "for i in range(10):\n    if i == 5:\n        break\n    print(i)",
    "outputExplain": "หยุด loop ด้วย break",
    "output": "หยุด loop ด้วย break",
    "basePoints": 340,
    "rewardPoints": 34,
    "timeLimit": 75
  },
  {
    "id": "python_21",
    "language": "python",
    "stage": 21,
    "difficulty": "medium",
    "title": "continue",
    "description": "ด่าน Python 21: continue",
    "usage": "ข้ามรอบด้วย continue",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "for i in range(6):\n    if i == 3:\n        continue\n    print(i)",
    "outputExplain": "ข้ามรอบด้วย continue",
    "output": "ข้ามรอบด้วย continue",
    "basePoints": 352,
    "rewardPoints": 35,
    "timeLimit": 77
  },
  {
    "id": "python_22",
    "language": "python",
    "stage": 22,
    "difficulty": "medium",
    "title": "function",
    "description": "ด่าน Python 22: function",
    "usage": "สร้างและเรียกฟังก์ชัน",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "def greet():\n    print(\"Hello\")\n\ngreet()",
    "outputExplain": "สร้างและเรียกฟังก์ชัน",
    "output": "สร้างและเรียกฟังก์ชัน",
    "basePoints": 364,
    "rewardPoints": 36,
    "timeLimit": 60
  },
  {
    "id": "python_23",
    "language": "python",
    "stage": 23,
    "difficulty": "medium",
    "title": "function parameter",
    "description": "ด่าน Python 23: function parameter",
    "usage": "ส่ง parameter เข้าฟังก์ชัน",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "def greet(name):\n    print(f\"Hello {name}\")\n\ngreet(\"Pisit\")",
    "outputExplain": "ส่ง parameter เข้าฟังก์ชัน",
    "output": "ส่ง parameter เข้าฟังก์ชัน",
    "basePoints": 376,
    "rewardPoints": 37,
    "timeLimit": 74
  },
  {
    "id": "python_24",
    "language": "python",
    "stage": 24,
    "difficulty": "medium",
    "title": "return",
    "description": "ด่าน Python 24: return",
    "usage": "คืนค่าจากฟังก์ชัน",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "def add(a, b):\n    return a + b\n\nresult = add(4, 6)\nprint(result)",
    "outputExplain": "คืนค่าจากฟังก์ชัน",
    "output": "คืนค่าจากฟังก์ชัน",
    "basePoints": 388,
    "rewardPoints": 38,
    "timeLimit": 78
  },
  {
    "id": "python_25",
    "language": "python",
    "stage": 25,
    "difficulty": "medium",
    "title": "default parameter",
    "description": "ด่าน Python 25: default parameter",
    "usage": "กำหนดค่าเริ่มต้น parameter",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "def greet(name=\"Student\"):\n    print(f\"Hello {name}\")\n\ngreet()\ngreet(\"Ann\")",
    "outputExplain": "กำหนดค่าเริ่มต้น parameter",
    "output": "กำหนดค่าเริ่มต้น parameter",
    "basePoints": 400,
    "rewardPoints": 39,
    "timeLimit": 86
  },
  {
    "id": "python_26",
    "language": "python",
    "stage": 26,
    "difficulty": "medium",
    "title": "tuple",
    "description": "ด่าน Python 26: tuple",
    "usage": "ใช้ tuple เก็บค่าคงรูป",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "point = (10, 20)\nprint(point[0], point[1])",
    "outputExplain": "ใช้ tuple เก็บค่าคงรูป",
    "output": "ใช้ tuple เก็บค่าคงรูป",
    "basePoints": 412,
    "rewardPoints": 41,
    "timeLimit": 61
  },
  {
    "id": "python_27",
    "language": "python",
    "stage": 27,
    "difficulty": "medium",
    "title": "set",
    "description": "ด่าน Python 27: set",
    "usage": "set ตัดค่าซ้ำ",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "skills = {\"HTML\", \"Python\", \"HTML\"}\nprint(skills)",
    "outputExplain": "set ตัดค่าซ้ำ",
    "output": "set ตัดค่าซ้ำ",
    "basePoints": 424,
    "rewardPoints": 42,
    "timeLimit": 66
  },
  {
    "id": "python_28",
    "language": "python",
    "stage": 28,
    "difficulty": "medium",
    "title": "dictionary",
    "description": "ด่าน Python 28: dictionary",
    "usage": "เก็บข้อมูลแบบ key-value",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "student = {\"name\": \"Ann\", \"score\": 90}\nprint(student[\"name\"])",
    "outputExplain": "เก็บข้อมูลแบบ key-value",
    "output": "เก็บข้อมูลแบบ key-value",
    "basePoints": 436,
    "rewardPoints": 43,
    "timeLimit": 75
  },
  {
    "id": "python_29",
    "language": "python",
    "stage": 29,
    "difficulty": "medium",
    "title": "dictionary loop",
    "description": "ด่าน Python 29: dictionary loop",
    "usage": "วน dictionary",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "scores = {\"Ann\": 80, \"Boy\": 70}\nfor name, score in scores.items():\n    print(name, score)",
    "outputExplain": "วน dictionary",
    "output": "วน dictionary",
    "basePoints": 448,
    "rewardPoints": 44,
    "timeLimit": 96
  },
  {
    "id": "python_30",
    "language": "python",
    "stage": 30,
    "difficulty": "medium",
    "title": "list comprehension",
    "description": "ด่าน Python 30: list comprehension",
    "usage": "สร้าง list แบบย่อ",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "squares = [n * n for n in range(1, 6)]\nprint(squares)",
    "outputExplain": "สร้าง list แบบย่อ",
    "output": "สร้าง list แบบย่อ",
    "basePoints": 460,
    "rewardPoints": 45,
    "timeLimit": 69
  },
  {
    "id": "python_31",
    "language": "python",
    "stage": 31,
    "difficulty": "medium",
    "title": "filter comprehension",
    "description": "ด่าน Python 31: filter comprehension",
    "usage": "กรองข้อมูลด้วย comprehension",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "scores = [40, 55, 72, 90]\npassed = [s for s in scores if s >= 50]\nprint(passed)",
    "outputExplain": "กรองข้อมูลด้วย comprehension",
    "output": "กรองข้อมูลด้วย comprehension",
    "basePoints": 472,
    "rewardPoints": 46,
    "timeLimit": 89
  },
  {
    "id": "python_32",
    "language": "python",
    "stage": 32,
    "difficulty": "medium",
    "title": "string methods",
    "description": "ด่าน Python 32: string methods",
    "usage": "ใช้ method ของ string",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "text = \"  Python Game  \"\nprint(text.strip().upper())",
    "outputExplain": "ใช้ method ของ string",
    "output": "ใช้ method ของ string",
    "basePoints": 484,
    "rewardPoints": 47,
    "timeLimit": 69
  },
  {
    "id": "python_33",
    "language": "python",
    "stage": 33,
    "difficulty": "medium",
    "title": "split join",
    "description": "ด่าน Python 33: split join",
    "usage": "แยกและรวมข้อความ",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "text = \"HTML,CSS,Python\"\nitems = text.split(\",\")\nprint(\" | \".join(items))",
    "outputExplain": "แยกและรวมข้อความ",
    "output": "แยกและรวมข้อความ",
    "basePoints": 496,
    "rewardPoints": 48,
    "timeLimit": 84
  },
  {
    "id": "python_34",
    "language": "python",
    "stage": 34,
    "difficulty": "medium",
    "title": "enumerate",
    "description": "ด่าน Python 34: enumerate",
    "usage": "วนพร้อมเลขลำดับ",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "languages = [\"HTML\", \"CSS\", \"Python\"]\nfor index, lang in enumerate(languages, start=1):\n    print(index, lang)",
    "outputExplain": "วนพร้อมเลขลำดับ",
    "output": "วนพร้อมเลขลำดับ",
    "basePoints": 508,
    "rewardPoints": 49,
    "timeLimit": 112
  },
  {
    "id": "python_35",
    "language": "python",
    "stage": 35,
    "difficulty": "medium",
    "title": "zip",
    "description": "ด่าน Python 35: zip",
    "usage": "จับคู่หลาย list",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "names = [\"Ann\", \"Boy\"]\nscores = [90, 75]\nfor name, score in zip(names, scores):\n    print(name, score)",
    "outputExplain": "จับคู่หลาย list",
    "output": "จับคู่หลาย list",
    "basePoints": 520,
    "rewardPoints": 50,
    "timeLimit": 106
  },
  {
    "id": "python_36",
    "language": "python",
    "stage": 36,
    "difficulty": "hard",
    "title": "try except",
    "description": "ด่าน Python 36: try except",
    "usage": "จัดการข้อผิดพลาด",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "try:\n    number = int(\"abc\")\nexcept ValueError:\n    print(\"Invalid number\")",
    "outputExplain": "จัดการข้อผิดพลาด",
    "output": "จัดการข้อผิดพลาด",
    "basePoints": 532,
    "rewardPoints": 52,
    "timeLimit": 86
  },
  {
    "id": "python_37",
    "language": "python",
    "stage": 37,
    "difficulty": "hard",
    "title": "raise",
    "description": "ด่าน Python 37: raise",
    "usage": "สร้าง error เมื่อข้อมูลไม่ถูกต้อง",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "def check_score(score):\n    if score < 0:\n        raise ValueError(\"Score must be positive\")\n    return score\n\nprint(check_score(80))",
    "outputExplain": "สร้าง error เมื่อข้อมูลไม่ถูกต้อง",
    "output": "สร้าง error เมื่อข้อมูลไม่ถูกต้อง",
    "basePoints": 544,
    "rewardPoints": 53,
    "timeLimit": 129
  },
  {
    "id": "python_38",
    "language": "python",
    "stage": 38,
    "difficulty": "hard",
    "title": "class พื้นฐาน",
    "description": "ด่าน Python 38: class พื้นฐาน",
    "usage": "สร้าง class และ object",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "class Student:\n    pass\n\nstudent = Student()\nprint(type(student).__name__)",
    "outputExplain": "สร้าง class และ object",
    "output": "สร้าง class และ object",
    "basePoints": 556,
    "rewardPoints": 55,
    "timeLimit": 85
  },
  {
    "id": "python_39",
    "language": "python",
    "stage": 39,
    "difficulty": "hard",
    "title": "constructor",
    "description": "ด่าน Python 39: constructor",
    "usage": "ใช้ __init__ กำหนดค่า object",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "class Student:\n    def __init__(self, name):\n        self.name = name\n\nstudent = Student(\"Ann\")\nprint(student.name)",
    "outputExplain": "ใช้ __init__ กำหนดค่า object",
    "output": "ใช้ __init__ กำหนดค่า object",
    "basePoints": 568,
    "rewardPoints": 56,
    "timeLimit": 116
  },
  {
    "id": "python_40",
    "language": "python",
    "stage": 40,
    "difficulty": "hard",
    "title": "method",
    "description": "ด่าน Python 40: method",
    "usage": "สร้าง method ภายใน class",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "class Counter:\n    def __init__(self):\n        self.value = 0\n\n    def add(self):\n        self.value += 1\n\ncounter = Counter()\ncounter.add()\nprint(counter.value)",
    "outputExplain": "สร้าง method ภายใน class",
    "output": "สร้าง method ภายใน class",
    "basePoints": 580,
    "rewardPoints": 57,
    "timeLimit": 150
  },
  {
    "id": "python_41",
    "language": "python",
    "stage": 41,
    "difficulty": "hard",
    "title": "inheritance",
    "description": "ด่าน Python 41: inheritance",
    "usage": "สืบทอด class",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "class Player:\n    def move(self):\n        print(\"Move\")\n\nclass Coder(Player):\n    def type_code(self):\n        print(\"Typing\")\n\ncoder = Coder()\ncoder.move()\ncoder.type_code()",
    "outputExplain": "สืบทอด class",
    "output": "สืบทอด class",
    "basePoints": 592,
    "rewardPoints": 58,
    "timeLimit": 160
  },
  {
    "id": "python_42",
    "language": "python",
    "stage": 42,
    "difficulty": "hard",
    "title": "property",
    "description": "ด่าน Python 42: property",
    "usage": "ใช้ property",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "class Player:\n    def __init__(self, score):\n        self._score = score\n\n    @property\n    def score(self):\n        return self._score\n\nplayer = Player(100)\nprint(player.score)",
    "outputExplain": "ใช้ property",
    "output": "ใช้ property",
    "basePoints": 604,
    "rewardPoints": 60,
    "timeLimit": 162
  },
  {
    "id": "python_43",
    "language": "python",
    "stage": 43,
    "difficulty": "hard",
    "title": "lambda",
    "description": "ด่าน Python 43: lambda",
    "usage": "ใช้ lambda ฟังก์ชันสั้น",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "numbers = [3, 1, 2]\nnumbers.sort(key=lambda n: n)\nprint(numbers)",
    "outputExplain": "ใช้ lambda ฟังก์ชันสั้น",
    "output": "ใช้ lambda ฟังก์ชันสั้น",
    "basePoints": 616,
    "rewardPoints": 61,
    "timeLimit": 78
  },
  {
    "id": "python_44",
    "language": "python",
    "stage": 44,
    "difficulty": "hard",
    "title": "map",
    "description": "ด่าน Python 44: map",
    "usage": "แปลงข้อมูลด้วย map",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "numbers = [1, 2, 3]\ndoubled = list(map(lambda n: n * 2, numbers))\nprint(doubled)",
    "outputExplain": "แปลงข้อมูลด้วย map",
    "output": "แปลงข้อมูลด้วย map",
    "basePoints": 628,
    "rewardPoints": 62,
    "timeLimit": 90
  },
  {
    "id": "python_45",
    "language": "python",
    "stage": 45,
    "difficulty": "hard",
    "title": "generator",
    "description": "ด่าน Python 45: generator",
    "usage": "สร้าง generator ด้วย yield",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "def countdown(n):\n    while n > 0:\n        yield n\n        n -= 1\n\nfor value in countdown(3):\n    print(value)",
    "outputExplain": "สร้าง generator ด้วย yield",
    "output": "สร้าง generator ด้วย yield",
    "basePoints": 640,
    "rewardPoints": 64,
    "timeLimit": 112
  },
  {
    "id": "python_46",
    "language": "python",
    "stage": 46,
    "difficulty": "hard",
    "title": "decorator",
    "description": "ด่าน Python 46: decorator",
    "usage": "ใช้ decorator ครอบฟังก์ชัน",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "def logger(func):\n    def wrapper():\n        print(\"Start\")\n        func()\n        print(\"End\")\n    return wrapper\n\n@logger\ndef play():\n    print(\"Playing\")\n\nplay()",
    "outputExplain": "ใช้ decorator ครอบฟังก์ชัน",
    "output": "ใช้ decorator ครอบฟังก์ชัน",
    "basePoints": 652,
    "rewardPoints": 65,
    "timeLimit": 153
  },
  {
    "id": "python_47",
    "language": "python",
    "stage": 47,
    "difficulty": "hard",
    "title": "dataclass",
    "description": "ด่าน Python 47: dataclass",
    "usage": "ใช้ dataclass ลด boilerplate",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "from dataclasses import dataclass\n\n@dataclass\nclass Player:\n    name: str\n    score: int\n\nplayer = Player(\"Ann\", 120)\nprint(player)",
    "outputExplain": "ใช้ dataclass ลด boilerplate",
    "output": "ใช้ dataclass ลด boilerplate",
    "basePoints": 664,
    "rewardPoints": 66,
    "timeLimit": 128
  },
  {
    "id": "python_48",
    "language": "python",
    "stage": 48,
    "difficulty": "hard",
    "title": "type hints",
    "description": "ด่าน Python 48: type hints",
    "usage": "ใช้ type hints",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "def average(scores: list[int]) -> float:\n    return sum(scores) / len(scores)\n\nprint(average([80, 90, 100]))",
    "outputExplain": "ใช้ type hints",
    "output": "ใช้ type hints",
    "basePoints": 676,
    "rewardPoints": 67,
    "timeLimit": 111
  },
  {
    "id": "python_49",
    "language": "python",
    "stage": 49,
    "difficulty": "hard",
    "title": "async function",
    "description": "ด่าน Python 49: async function",
    "usage": "รู้จัก async/await",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "import asyncio\n\nasync def load_data():\n    await asyncio.sleep(0.1)\n    return \"ready\"\n\nprint(asyncio.run(load_data()))",
    "outputExplain": "รู้จัก async/await",
    "output": "รู้จัก async/await",
    "basePoints": 688,
    "rewardPoints": 69,
    "timeLimit": 119
  },
  {
    "id": "python_50",
    "language": "python",
    "stage": 50,
    "difficulty": "hard",
    "title": "Mini Game Logic",
    "description": "ด่าน Python 50: Mini Game Logic",
    "usage": "ด่านสุดท้ายจำลอง logic เกมตรวจตัวอักษร",
    "benefit": "ฝึกไวยากรณ์ Python และการอ่านโค้ดแบบไต่ระดับ",
    "code": "class TypingGame:\n    def __init__(self, target):\n        self.target = target\n        self.position = 0\n        self.mistakes = 0\n\n    def type_char(self, char):\n        expected = self.target[self.position]\n        if char == expected:\n            self.position += 1\n            return True\n        self.mistakes += 1\n        return False\n\n    def completed(self):\n        return self.position == len(self.target)\n\ngame = TypingGame(\"code\")\nfor char in \"code\":\n    game.type_char(char)\n\nprint(game.completed(), game.mistakes)",
    "outputExplain": "ด่านสุดท้ายจำลอง logic เกมตรวจตัวอักษร",
    "output": "ด่านสุดท้ายจำลอง logic เกมตรวจตัวอักษร",
    "basePoints": 700,
    "rewardPoints": 70,
    "timeLimit": 300
  }
];
