export const HTML_LEVELS = [
  {
    "id": "html_01",
    "language": "html",
    "stage": 1,
    "difficulty": "easy",
    "title": "หัวข้อและย่อหน้า",
    "description": "ด่าน HTML 1: หัวข้อและย่อหน้า",
    "usage": "ใช้ h1 เป็นหัวข้อหลักและ p เป็นย่อหน้า",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<h1>Hello HTML</h1>\n<p>เริ่มต้นเรียนรู้ HTML</p>",
    "outputExplain": "ใช้ h1 เป็นหัวข้อหลักและ p เป็นย่อหน้า",
    "basePoints": 110,
    "rewardPoints": 12,
    "timeLimit": 66
  },
  {
    "id": "html_02",
    "language": "html",
    "stage": 2,
    "difficulty": "easy",
    "title": "ตัวหนาและตัวเอียง",
    "description": "ด่าน HTML 2: ตัวหนาและตัวเอียง",
    "usage": "strong เน้นความสำคัญ ส่วน em เน้นข้อความ",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<p>เรียน <strong>HTML</strong> แบบ <em>เข้าใจง่าย</em></p>",
    "outputExplain": "strong เน้นความสำคัญ ส่วน em เน้นข้อความ",
    "basePoints": 120,
    "rewardPoints": 13,
    "timeLimit": 73
  },
  {
    "id": "html_03",
    "language": "html",
    "stage": 3,
    "difficulty": "easy",
    "title": "ลิงก์",
    "description": "ด่าน HTML 3: ลิงก์",
    "usage": "แท็ก a ใช้สร้างลิงก์",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<a href=\"https://example.com\">เปิดเว็บไซต์ตัวอย่าง</a>",
    "outputExplain": "แท็ก a ใช้สร้างลิงก์",
    "basePoints": 130,
    "rewardPoints": 15,
    "timeLimit": 70
  },
  {
    "id": "html_04",
    "language": "html",
    "stage": 4,
    "difficulty": "easy",
    "title": "รูปภาพ",
    "description": "ด่าน HTML 4: รูปภาพ",
    "usage": "img ใช้แสดงรูปและ alt อธิบายรูป",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<img src=\"https://picsum.photos/240/120\" alt=\"ภาพตัวอย่าง\">",
    "outputExplain": "img ใช้แสดงรูปและ alt อธิบายรูป",
    "basePoints": 140,
    "rewardPoints": 16,
    "timeLimit": 74
  },
  {
    "id": "html_05",
    "language": "html",
    "stage": 5,
    "difficulty": "easy",
    "title": "รายการไม่เรียงลำดับ",
    "description": "ด่าน HTML 5: รายการไม่เรียงลำดับ",
    "usage": "ul และ li ใช้สร้างรายการแบบจุด",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<ul>\n  <li>HTML</li>\n  <li>CSS</li>\n  <li>JavaScript</li>\n</ul>",
    "outputExplain": "ul และ li ใช้สร้างรายการแบบจุด",
    "basePoints": 150,
    "rewardPoints": 17,
    "timeLimit": 77
  },
  {
    "id": "html_06",
    "language": "html",
    "stage": 6,
    "difficulty": "easy",
    "title": "รายการเรียงลำดับ",
    "description": "ด่าน HTML 6: รายการเรียงลำดับ",
    "usage": "ol ใช้สร้างรายการมีลำดับ",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<ol>\n  <li>วางแผน</li>\n  <li>เขียนโค้ด</li>\n  <li>ทดสอบ</li>\n</ol>",
    "outputExplain": "ol ใช้สร้างรายการมีลำดับ",
    "basePoints": 160,
    "rewardPoints": 18,
    "timeLimit": 79
  },
  {
    "id": "html_07",
    "language": "html",
    "stage": 7,
    "difficulty": "easy",
    "title": "เส้นคั่นและขึ้นบรรทัด",
    "description": "ด่าน HTML 7: เส้นคั่นและขึ้นบรรทัด",
    "usage": "br ขึ้นบรรทัดใหม่และ hr สร้างเส้นแบ่ง",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<p>บรรทัดแรก<br>บรรทัดที่สอง</p>\n<hr>",
    "outputExplain": "br ขึ้นบรรทัดใหม่และ hr สร้างเส้นแบ่ง",
    "basePoints": 170,
    "rewardPoints": 20,
    "timeLimit": 57
  },
  {
    "id": "html_08",
    "language": "html",
    "stage": 8,
    "difficulty": "easy",
    "title": "กล่อง div",
    "description": "ด่าน HTML 8: กล่อง div",
    "usage": "div ใช้จัดกลุ่มองค์ประกอบ",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<div class=\"card\">\n  <h2>Card</h2>\n  <p>เนื้อหาภายในการ์ด</p>\n</div>",
    "outputExplain": "div ใช้จัดกลุ่มองค์ประกอบ",
    "basePoints": 180,
    "rewardPoints": 21,
    "timeLimit": 81
  },
  {
    "id": "html_09",
    "language": "html",
    "stage": 9,
    "difficulty": "easy",
    "title": "span ในข้อความ",
    "description": "ด่าน HTML 9: span ในข้อความ",
    "usage": "span ใช้ครอบข้อความเฉพาะส่วน",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<p>คะแนน: <span class=\"score\">100</span> แต้ม</p>",
    "outputExplain": "span ใช้ครอบข้อความเฉพาะส่วน",
    "basePoints": 190,
    "rewardPoints": 22,
    "timeLimit": 66
  },
  {
    "id": "html_10",
    "language": "html",
    "stage": 10,
    "difficulty": "easy",
    "title": "ตารางพื้นฐาน",
    "description": "ด่าน HTML 10: ตารางพื้นฐาน",
    "usage": "table, tr, th, td ใช้สร้างตาราง",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<table>\n  <tr><th>ชื่อ</th><th>คะแนน</th></tr>\n  <tr><td>Ann</td><td>90</td></tr>\n</table>",
    "outputExplain": "table, tr, th, td ใช้สร้างตาราง",
    "basePoints": 200,
    "rewardPoints": 24,
    "timeLimit": 97
  },
  {
    "id": "html_11",
    "language": "html",
    "stage": 11,
    "difficulty": "easy",
    "title": "หัวตารางและตัวตาราง",
    "description": "ด่าน HTML 11: หัวตารางและตัวตาราง",
    "usage": "thead และ tbody แยกส่วนหัวและข้อมูล",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<table>\n  <thead><tr><th>วิชา</th><th>เกรด</th></tr></thead>\n  <tbody><tr><td>Programming</td><td>A</td></tr></tbody>\n</table>",
    "outputExplain": "thead และ tbody แยกส่วนหัวและข้อมูล",
    "basePoints": 210,
    "rewardPoints": 25,
    "timeLimit": 124
  },
  {
    "id": "html_12",
    "language": "html",
    "stage": 12,
    "difficulty": "easy",
    "title": "ปุ่ม",
    "description": "ด่าน HTML 12: ปุ่ม",
    "usage": "button ใช้สร้างปุ่ม",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<button type=\"button\">เริ่มเกม</button>",
    "outputExplain": "button ใช้สร้างปุ่ม",
    "basePoints": 220,
    "rewardPoints": 26,
    "timeLimit": 59
  },
  {
    "id": "html_13",
    "language": "html",
    "stage": 13,
    "difficulty": "easy",
    "title": "ช่องข้อความ",
    "description": "ด่าน HTML 13: ช่องข้อความ",
    "usage": "label เชื่อมกับ input เพื่อรับข้อมูล",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<label for=\"name\">ชื่อ</label>\n<input id=\"name\" type=\"text\">",
    "outputExplain": "label เชื่อมกับ input เพื่อรับข้อมูล",
    "basePoints": 230,
    "rewardPoints": 27,
    "timeLimit": 75
  },
  {
    "id": "html_14",
    "language": "html",
    "stage": 14,
    "difficulty": "easy",
    "title": "ช่องอีเมล",
    "description": "ด่าน HTML 14: ช่องอีเมล",
    "usage": "input email ช่วยตรวจรูปแบบอีเมล",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<label for=\"email\">อีเมล</label>\n<input id=\"email\" type=\"email\" required>",
    "outputExplain": "input email ช่วยตรวจรูปแบบอีเมล",
    "basePoints": 240,
    "rewardPoints": 29,
    "timeLimit": 84
  },
  {
    "id": "html_15",
    "language": "html",
    "stage": 15,
    "difficulty": "easy",
    "title": "รหัสผ่าน",
    "description": "ด่าน HTML 15: รหัสผ่าน",
    "usage": "password ซ่อนตัวอักษรขณะพิมพ์",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<label for=\"password\">รหัสผ่าน</label>\n<input id=\"password\" type=\"password\" minlength=\"6\">",
    "outputExplain": "password ซ่อนตัวอักษรขณะพิมพ์",
    "basePoints": 250,
    "rewardPoints": 30,
    "timeLimit": 97
  },
  {
    "id": "html_16",
    "language": "html",
    "stage": 16,
    "difficulty": "medium",
    "title": "ตัวเลือก select",
    "description": "ด่าน HTML 16: ตัวเลือก select",
    "usage": "select และ option สร้างรายการเลือก",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<label for=\"level\">ระดับ</label>\n<select id=\"level\">\n  <option>ง่าย</option>\n  <option>ปานกลาง</option>\n  <option>ยาก</option>\n</select>",
    "outputExplain": "select และ option สร้างรายการเลือก",
    "basePoints": 260,
    "rewardPoints": 30,
    "timeLimit": 132
  },
  {
    "id": "html_17",
    "language": "html",
    "stage": 17,
    "difficulty": "medium",
    "title": "checkbox",
    "description": "ด่าน HTML 17: checkbox",
    "usage": "checkbox ใช้เลือกค่าแบบเปิด/ปิด",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<label>\n  <input type=\"checkbox\">\n  ยอมรับเงื่อนไข\n</label>",
    "outputExplain": "checkbox ใช้เลือกค่าแบบเปิด/ปิด",
    "basePoints": 270,
    "rewardPoints": 31,
    "timeLimit": 74
  },
  {
    "id": "html_18",
    "language": "html",
    "stage": 18,
    "difficulty": "medium",
    "title": "radio",
    "description": "ด่าน HTML 18: radio",
    "usage": "radio ใช้เลือกหนึ่งค่าจากกลุ่ม",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<label><input type=\"radio\" name=\"mode\"> Classic</label>\n<label><input type=\"radio\" name=\"mode\"> PVP</label>",
    "outputExplain": "radio ใช้เลือกหนึ่งค่าจากกลุ่ม",
    "basePoints": 280,
    "rewardPoints": 32,
    "timeLimit": 110
  },
  {
    "id": "html_19",
    "language": "html",
    "stage": 19,
    "difficulty": "medium",
    "title": "textarea",
    "description": "ด่าน HTML 19: textarea",
    "usage": "textarea ใช้รับข้อความหลายบรรทัด",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<label for=\"note\">หมายเหตุ</label>\n<textarea id=\"note\" rows=\"4\"></textarea>",
    "outputExplain": "textarea ใช้รับข้อความหลายบรรทัด",
    "basePoints": 290,
    "rewardPoints": 33,
    "timeLimit": 86
  },
  {
    "id": "html_20",
    "language": "html",
    "stage": 20,
    "difficulty": "medium",
    "title": "ฟอร์มสมัคร",
    "description": "ด่าน HTML 20: ฟอร์มสมัคร",
    "usage": "form รวมช่องข้อมูลและปุ่มส่ง",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<form>\n  <label for=\"student\">รหัสนักศึกษา</label>\n  <input id=\"student\" required>\n  <button type=\"submit\">สมัคร</button>\n</form>",
    "outputExplain": "form รวมช่องข้อมูลและปุ่มส่ง",
    "basePoints": 300,
    "rewardPoints": 34,
    "timeLimit": 126
  },
  {
    "id": "html_21",
    "language": "html",
    "stage": 21,
    "difficulty": "medium",
    "title": "header",
    "description": "ด่าน HTML 21: header",
    "usage": "header คือส่วนหัวของหน้า/ส่วน",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<header>\n  <h1>Code Typing</h1>\n  <p>ฝึกพิมพ์โค้ดให้แม่นยำ</p>\n</header>",
    "outputExplain": "header คือส่วนหัวของหน้า/ส่วน",
    "basePoints": 310,
    "rewardPoints": 35,
    "timeLimit": 84
  },
  {
    "id": "html_22",
    "language": "html",
    "stage": 22,
    "difficulty": "medium",
    "title": "nav",
    "description": "ด่าน HTML 22: nav",
    "usage": "nav ใช้กับชุดลิงก์นำทาง",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<nav>\n  <a href=\"#home\">หน้าแรก</a>\n  <a href=\"#lesson\">บทเรียน</a>\n  <a href=\"#game\">เกม</a>\n</nav>",
    "outputExplain": "nav ใช้กับชุดลิงก์นำทาง",
    "basePoints": 320,
    "rewardPoints": 36,
    "timeLimit": 105
  },
  {
    "id": "html_23",
    "language": "html",
    "stage": 23,
    "difficulty": "medium",
    "title": "main",
    "description": "ด่าน HTML 23: main",
    "usage": "main ครอบเนื้อหาหลัก",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<main>\n  <h1>บทเรียน HTML</h1>\n  <p>เนื้อหาหลักของหน้า</p>\n</main>",
    "outputExplain": "main ครอบเนื้อหาหลัก",
    "basePoints": 330,
    "rewardPoints": 37,
    "timeLimit": 79
  },
  {
    "id": "html_24",
    "language": "html",
    "stage": 24,
    "difficulty": "medium",
    "title": "section",
    "description": "ด่าน HTML 24: section",
    "usage": "section แบ่งเนื้อหาเป็นหมวด",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<section>\n  <h2>บทที่ 1</h2>\n  <p>พื้นฐาน HTML</p>\n</section>",
    "outputExplain": "section แบ่งเนื้อหาเป็นหมวด",
    "basePoints": 340,
    "rewardPoints": 38,
    "timeLimit": 75
  },
  {
    "id": "html_25",
    "language": "html",
    "stage": 25,
    "difficulty": "medium",
    "title": "article",
    "description": "ด่าน HTML 25: article",
    "usage": "article เหมาะกับเนื้อหาอิสระ",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<article>\n  <h2>ข่าวการเขียนโปรแกรม</h2>\n  <p>เนื้อหาที่อยู่ได้ด้วยตัวเอง</p>\n</article>",
    "outputExplain": "article เหมาะกับเนื้อหาอิสระ",
    "basePoints": 350,
    "rewardPoints": 39,
    "timeLimit": 96
  },
  {
    "id": "html_26",
    "language": "html",
    "stage": 26,
    "difficulty": "medium",
    "title": "aside",
    "description": "ด่าน HTML 26: aside",
    "usage": "aside คือข้อมูลเสริมจากเนื้อหาหลัก",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<main>\n  <article>เนื้อหาหลัก</article>\n  <aside>คำแนะนำเพิ่มเติม</aside>\n</main>",
    "outputExplain": "aside คือข้อมูลเสริมจากเนื้อหาหลัก",
    "basePoints": 360,
    "rewardPoints": 41,
    "timeLimit": 90
  },
  {
    "id": "html_27",
    "language": "html",
    "stage": 27,
    "difficulty": "medium",
    "title": "footer",
    "description": "ด่าน HTML 27: footer",
    "usage": "footer คือส่วนท้าย",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<footer>\n  <p>© 2026 Code Academy</p>\n</footer>",
    "outputExplain": "footer คือส่วนท้าย",
    "basePoints": 370,
    "rewardPoints": 42,
    "timeLimit": 65
  },
  {
    "id": "html_28",
    "language": "html",
    "stage": 28,
    "difficulty": "medium",
    "title": "figure",
    "description": "ด่าน HTML 28: figure",
    "usage": "figure จัดกลุ่มสื่อกับคำอธิบาย",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<figure>\n  <img src=\"https://picsum.photos/220/100\" alt=\"ตัวอย่าง\">\n  <figcaption>ภาพประกอบบทเรียน</figcaption>\n</figure>",
    "outputExplain": "figure จัดกลุ่มสื่อกับคำอธิบาย",
    "basePoints": 380,
    "rewardPoints": 43,
    "timeLimit": 120
  },
  {
    "id": "html_29",
    "language": "html",
    "stage": 29,
    "difficulty": "medium",
    "title": "details",
    "description": "ด่าน HTML 29: details",
    "usage": "details สร้างส่วนเปิด/ปิด",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<details>\n  <summary>ดูคำอธิบาย</summary>\n  <p>HTML คือภาษาสำหรับโครงสร้างเว็บ</p>\n</details>",
    "outputExplain": "details สร้างส่วนเปิด/ปิด",
    "basePoints": 390,
    "rewardPoints": 44,
    "timeLimit": 99
  },
  {
    "id": "html_30",
    "language": "html",
    "stage": 30,
    "difficulty": "medium",
    "title": "progress",
    "description": "ด่าน HTML 30: progress",
    "usage": "progress แสดงความคืบหน้า",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<label for=\"progress\">ความคืบหน้า</label>\n<progress id=\"progress\" value=\"65\" max=\"100\">65%</progress>",
    "outputExplain": "progress แสดงความคืบหน้า",
    "basePoints": 400,
    "rewardPoints": 45,
    "timeLimit": 105
  },
  {
    "id": "html_31",
    "language": "html",
    "stage": 31,
    "difficulty": "medium",
    "title": "meter",
    "description": "ด่าน HTML 31: meter",
    "usage": "meter แสดงค่าภายในช่วง",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<label for=\"accuracy\">Accuracy</label>\n<meter id=\"accuracy\" min=\"0\" max=\"100\" value=\"92\">92%</meter>",
    "outputExplain": "meter แสดงค่าภายในช่วง",
    "basePoints": 410,
    "rewardPoints": 46,
    "timeLimit": 105
  },
  {
    "id": "html_32",
    "language": "html",
    "stage": 32,
    "difficulty": "medium",
    "title": "time",
    "description": "ด่าน HTML 32: time",
    "usage": "time ระบุวันเวลาอย่างมีความหมาย",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<p>เริ่มเรียนวันที่ <time datetime=\"2026-08-12\">12 สิงหาคม 2569</time></p>",
    "outputExplain": "time ระบุวันเวลาอย่างมีความหมาย",
    "basePoints": 420,
    "rewardPoints": 47,
    "timeLimit": 85
  },
  {
    "id": "html_33",
    "language": "html",
    "stage": 33,
    "difficulty": "medium",
    "title": "mark",
    "description": "ด่าน HTML 33: mark",
    "usage": "mark ไฮไลต์ข้อความ",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<p>คำสำคัญคือ <mark>semantic HTML</mark></p>",
    "outputExplain": "mark ไฮไลต์ข้อความ",
    "basePoints": 430,
    "rewardPoints": 48,
    "timeLimit": 63
  },
  {
    "id": "html_34",
    "language": "html",
    "stage": 34,
    "difficulty": "medium",
    "title": "code",
    "description": "ด่าน HTML 34: code",
    "usage": "code ใช้แสดงข้อความโค้ด",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<p>ใช้คำสั่ง <code>&lt;h1&gt;</code> เพื่อสร้างหัวข้อ</p>",
    "outputExplain": "code ใช้แสดงข้อความโค้ด",
    "basePoints": 440,
    "rewardPoints": 49,
    "timeLimit": 72
  },
  {
    "id": "html_35",
    "language": "html",
    "stage": 35,
    "difficulty": "medium",
    "title": "pre",
    "description": "ด่าน HTML 35: pre",
    "usage": "pre รักษาช่องว่างและบรรทัด",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<pre><code>&lt;h1&gt;Hello&lt;/h1&gt;\n&lt;p&gt;World&lt;/p&gt;</code></pre>",
    "outputExplain": "pre รักษาช่องว่างและบรรทัด",
    "basePoints": 450,
    "rewardPoints": 50,
    "timeLimit": 86
  },
  {
    "id": "html_36",
    "language": "html",
    "stage": 36,
    "difficulty": "hard",
    "title": "iframe",
    "description": "ด่าน HTML 36: iframe",
    "usage": "iframe ฝังเอกสารอื่น",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<iframe src=\"https://example.com\" title=\"เว็บไซต์ตัวอย่าง\"></iframe>",
    "outputExplain": "iframe ฝังเอกสารอื่น",
    "basePoints": 460,
    "rewardPoints": 52,
    "timeLimit": 81
  },
  {
    "id": "html_37",
    "language": "html",
    "stage": 37,
    "difficulty": "hard",
    "title": "audio",
    "description": "ด่าน HTML 37: audio",
    "usage": "audio ฝังเสียงพร้อม controls",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<audio controls>\n  <source src=\"audio.mp3\" type=\"audio/mpeg\">\n  Browser ไม่รองรับเสียง\n</audio>",
    "outputExplain": "audio ฝังเสียงพร้อม controls",
    "basePoints": 470,
    "rewardPoints": 53,
    "timeLimit": 101
  },
  {
    "id": "html_38",
    "language": "html",
    "stage": 38,
    "difficulty": "hard",
    "title": "video",
    "description": "ด่าน HTML 38: video",
    "usage": "video ฝังวิดีโอ",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<video controls width=\"320\">\n  <source src=\"video.mp4\" type=\"video/mp4\">\n  Browser ไม่รองรับวิดีโอ\n</video>",
    "outputExplain": "video ฝังวิดีโอ",
    "basePoints": 480,
    "rewardPoints": 55,
    "timeLimit": 110
  },
  {
    "id": "html_39",
    "language": "html",
    "stage": 39,
    "difficulty": "hard",
    "title": "picture",
    "description": "ด่าน HTML 39: picture",
    "usage": "picture เลือกรูปตามเงื่อนไข",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<picture>\n  <source media=\"(min-width: 800px)\" srcset=\"large.jpg\">\n  <img src=\"small.jpg\" alt=\"Responsive image\">\n</picture>",
    "outputExplain": "picture เลือกรูปตามเงื่อนไข",
    "basePoints": 490,
    "rewardPoints": 56,
    "timeLimit": 123
  },
  {
    "id": "html_40",
    "language": "html",
    "stage": 40,
    "difficulty": "hard",
    "title": "data attributes",
    "description": "ด่าน HTML 40: data attributes",
    "usage": "data-* เก็บข้อมูลเพิ่มเติมบน element",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<button data-level=\"10\" data-mode=\"classic\">เล่น Level 10</button>",
    "outputExplain": "data-* เก็บข้อมูลเพิ่มเติมบน element",
    "basePoints": 500,
    "rewardPoints": 57,
    "timeLimit": 79
  },
  {
    "id": "html_41",
    "language": "html",
    "stage": 41,
    "difficulty": "hard",
    "title": "ARIA label",
    "description": "ด่าน HTML 41: ARIA label",
    "usage": "aria-label ช่วย Screen Reader",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<button aria-label=\"ปิดหน้าต่าง\">×</button>",
    "outputExplain": "aria-label ช่วย Screen Reader",
    "basePoints": 510,
    "rewardPoints": 58,
    "timeLimit": 62
  },
  {
    "id": "html_42",
    "language": "html",
    "stage": 42,
    "difficulty": "hard",
    "title": "fieldset",
    "description": "ด่าน HTML 42: fieldset",
    "usage": "fieldset จัดกลุ่มช่องฟอร์ม",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<form>\n  <fieldset>\n    <legend>ข้อมูลผู้เล่น</legend>\n    <label>ชื่อ <input type=\"text\"></label>\n  </fieldset>\n</form>",
    "outputExplain": "fieldset จัดกลุ่มช่องฟอร์ม",
    "basePoints": 520,
    "rewardPoints": 60,
    "timeLimit": 120
  },
  {
    "id": "html_43",
    "language": "html",
    "stage": 43,
    "difficulty": "hard",
    "title": "datalist",
    "description": "ด่าน HTML 43: datalist",
    "usage": "datalist ให้คำแนะนำใน input",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<label for=\"lang\">ภาษา</label>\n<input id=\"lang\" list=\"languages\">\n<datalist id=\"languages\">\n  <option value=\"HTML\">\n  <option value=\"Python\">\n</datalist>",
    "outputExplain": "datalist ให้คำแนะนำใน input",
    "basePoints": 530,
    "rewardPoints": 61,
    "timeLimit": 144
  },
  {
    "id": "html_44",
    "language": "html",
    "stage": 44,
    "difficulty": "hard",
    "title": "output",
    "description": "ด่าน HTML 44: output",
    "usage": "output แสดงผลการคำนวณ",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<form oninput=\"result.value=Number(a.value)+Number(b.value)\">\n  <input id=\"a\" type=\"number\" value=\"2\"> +\n  <input id=\"b\" type=\"number\" value=\"3\"> =\n  <output name=\"result\">5</output>\n</form>",
    "outputExplain": "output แสดงผลการคำนวณ",
    "basePoints": 540,
    "rewardPoints": 62,
    "timeLimit": 172
  },
  {
    "id": "html_45",
    "language": "html",
    "stage": 45,
    "difficulty": "hard",
    "title": "template",
    "description": "ด่าน HTML 45: template",
    "usage": "template เก็บ markup ที่ยังไม่ render",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<template id=\"cardTemplate\">\n  <article class=\"card\">\n    <h2>Template Card</h2>\n  </article>\n</template>",
    "outputExplain": "template เก็บ markup ที่ยังไม่ render",
    "basePoints": 550,
    "rewardPoints": 64,
    "timeLimit": 108
  },
  {
    "id": "html_46",
    "language": "html",
    "stage": 46,
    "difficulty": "hard",
    "title": "dialog",
    "description": "ด่าน HTML 46: dialog",
    "usage": "dialog ใช้สร้างกล่องโต้ตอบ",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<dialog open>\n  <h2>Level Complete</h2>\n  <p>คุณผ่านด่านแล้ว</p>\n  <button>ตกลง</button>\n</dialog>",
    "outputExplain": "dialog ใช้สร้างกล่องโต้ตอบ",
    "basePoints": 560,
    "rewardPoints": 65,
    "timeLimit": 103
  },
  {
    "id": "html_47",
    "language": "html",
    "stage": 47,
    "difficulty": "hard",
    "title": "meta viewport",
    "description": "ด่าน HTML 47: meta viewport",
    "usage": "meta viewport ทำให้หน้าเว็บรองรับมือถือ",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<!DOCTYPE html>\n<html>\n<head>\n  <meta charset=\"UTF-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n  <title>Responsive Page</title>\n</head>\n<body>\n  <h1>Responsive HTML</h1>\n</body>\n</html>",
    "outputExplain": "meta viewport ทำให้หน้าเว็บรองรับมือถือ",
    "basePoints": 570,
    "rewardPoints": 66,
    "timeLimit": 193
  },
  {
    "id": "html_48",
    "language": "html",
    "stage": 48,
    "difficulty": "hard",
    "title": "หน้า Profile",
    "description": "ด่าน HTML 48: หน้า Profile",
    "usage": "รวม semantic elements เป็นหน้าโปรไฟล์",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<main>\n  <article class=\"profile\">\n    <img src=\"avatar.png\" alt=\"รูปผู้เล่น\">\n    <h1>Pisit</h1>\n    <p>Level 25 · 2,450 Points</p>\n    <button>แก้ไขตัวละคร</button>\n  </article>\n</main>",
    "outputExplain": "รวม semantic elements เป็นหน้าโปรไฟล์",
    "basePoints": 580,
    "rewardPoints": 67,
    "timeLimit": 170
  },
  {
    "id": "html_49",
    "language": "html",
    "stage": 49,
    "difficulty": "hard",
    "title": "หน้า Dashboard",
    "description": "ด่าน HTML 49: หน้า Dashboard",
    "usage": "รวมองค์ประกอบเป็น Dashboard",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<header><h1>Student Dashboard</h1></header>\n<main>\n  <section>\n    <h2>สถิติ</h2>\n    <ul>\n      <li>WPM: 52</li>\n      <li>Accuracy: 98%</li>\n      <li>Points: 3200</li>\n    </ul>\n  </section>\n</main>",
    "outputExplain": "รวมองค์ประกอบเป็น Dashboard",
    "basePoints": 590,
    "rewardPoints": 69,
    "timeLimit": 180
  },
  {
    "id": "html_50",
    "language": "html",
    "stage": 50,
    "difficulty": "hard",
    "title": "หน้าเกม Semantic",
    "description": "ด่าน HTML 50: หน้าเกม Semantic",
    "usage": "ด่านสุดท้ายรวมโครงสร้าง HTML5 หลายส่วน",
    "benefit": "ฝึกอ่านและพิมพ์โครงสร้าง HTML ให้แม่นยำ พร้อมเข้าใจหน้าที่ของแท็ก",
    "code": "<!DOCTYPE html>\n<html lang=\"th\">\n<head>\n  <meta charset=\"UTF-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n  <title>Code Typing Arena</title>\n</head>\n<body>\n  <header>\n    <h1>Code Typing Arena</h1>\n    <nav><a href=\"#classic\">Classic</a> <a href=\"#pvp\">PVP</a></nav>\n  </header>\n  <main>\n    <section id=\"classic\">\n      <h2>Classic Mode</h2>\n      <p>พิมพ์โค้ดให้ถูกต้องและเร็วที่สุด</p>\n      <button type=\"button\">เริ่มเกม</button>\n    </section>\n  </main>\n  <footer>© 2026 Nangrong Technical College</footer>\n</body>\n</html>",
    "outputExplain": "ด่านสุดท้ายรวมโครงสร้าง HTML5 หลายส่วน",
    "basePoints": 600,
    "rewardPoints": 70,
    "timeLimit": 300
  }
];
